spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/mysql
        username: root
        password: mypass1234
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
            



